# Análise de Dados

## Importações

In [2]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

## Medições Brutas de Diâmetro (cm)

In [18]:
measurement_data = {
  'm1':  [0.71, 0.57, 0.58, 0.73, 0.59, 0.70, 0.60],
  'm2':  [0.71, 1.03, 0.89, 0.91, 1.00, 0.92, 1.01],
  'm4':  [1.17, 1.18, 1.30, 1.17, 1.01, 1.25, 1.19],
  'm8':  [1.52, 1.21, 1.49, 1.21, 1.09, 1.45, 1.29],
  'm16': [1.95, 2.11, 2.02, 1.95, 1.92, 2.29, 1.80],
  'm32': [2.81, 2.57, 2.44, 2.86, 2.59, 2.51, 3.12],
  'm64': [3.03, 3.97, 3.80, 2.17, 3.92, 2.78, 3.07],
}

measurement_dataframe = pd.DataFrame(measurement_data).T
measurement_dataframe.columns = [f"med_{i+1}" for i in range(7)]
measurement_dataframe.index.name = "amostra"
measurement_dataframe.to_csv("measurement_data.csv")
measurement_dataframe

         med_1  med_2  med_3  med_4  med_5  med_6  med_7
amostra
m1        0.71   0.57   0.58   0.73   0.59   0.70   0.60
m2        0.71   1.03   0.89   0.91   1.00   0.92   1.01
m4        1.17   1.18   1.30   1.17   1.01   1.25   1.19
m8        1.52   1.21   1.49   1.21   1.09   1.45   1.29
m16       1.95   2.11   2.02   1.95   1.92   2.29   1.80
m32       2.81   2.57   2.44   2.86   2.59   2.51   3.12
m64       3.03   3.97   3.80   2.17   3.92   2.78   3.07

## Análise Estatística das Medições de Diâmetro

- Média Aritmética
- Desvio Padrão Amostral
- Erro Padrão da Média

In [23]:
reading_measurement_data = pd.read_csv("measurement_data.csv", index_col="amostra")

def sem(series: pd.Series) -> float:
    return series.std(ddof=1) / np.sqrt(len(series))

stats = reading_measurement_data.agg(["mean", "std", sem], axis=1)

stats.columns = ["Média (cm)", "Desvio Padrão (cm)", "Erro Padrão (cm)"]
stats.index.name = "Amostra"

stats

         Média (cm)  Desvio Padrão (cm)  Erro Padrão (cm)
Amostra
m1         0.640000            0.069761          0.026367
m2         0.924286            0.109218          0.041281
m4         1.181429            0.089894          0.033977
m8         1.322857            0.165198          0.062439
m16        2.005714            0.156935          0.059316
m32        2.700000            0.240416          0.090869
m64        3.248571            0.675510          0.255319